// .\hiddencentral1_beta.res
// .\Author TheBard108
gfx/env/ionusbk.bmp
gfx/env/ionusdn.bmp
gfx/env/ionusft.bmp
gfx/env/ionuslf.bmp
gfx/env/ionusrt.bmp
gfx/env/ionusup.bmp
gfx/env/ionusbk.tga
gfx/env/ionusdn.tga
gfx/env/ionusft.tga
gfx/env/ionuslf.tga
gfx/env/ionusrt.tga
gfx/env/ionusup.tga
maps/hiddencentral1_beta.cfg
maps/hiddencentral1_beta.gmr
maps/hiddencentral1_beta.res
maps/hiddencentral1_beta_motd.txt
models/tb/tb-maze8/bench2b.mdl
models/tb/tb-maze8/rubbish-bin.mdl
models/tb/tb-maze8/chair_row.mdl
models/tb/tb-maze8/phone-wall.mdl
models/tb/tb-maze8/washingmachine-old.mdl
models/tb/tb-maze8/office-bin.mdl
models/tb/tb-maze8/dryer-old.mdl
models/tb/tb-maze8/landry-bag.mdl
models/tb/tb-maze8/paper1.mdl
models/tb/tb-maze8/paper3.mdl
models/tb/tb-maze8/paper4.mdl
models/tb/tb-maze8/paper2.mdl
models/tb/tb-maze8/dash-con.mdl
models/tb/tb-maze8/table-iron.mdl
models/tb/tb-maze8/bag-holdel.mdl
models/tb/tb-maze8/gunrack1.mdl
models/tb/tb-maze8/w_vulcan.mdl
models/tb/tb-maze8/w_bi-pod.mdl
models/tb/tb-maze8/w_c4.mdl
models/tb/tb-maze8/ammo-box2.mdl
models/tb/tb-maze8/comp-notebook.mdl
models/tb/tb-maze8/w_kevlar.mdl
models/tb/tb-maze8/barney_helmet.mdl
models/tb/tb-maze8/wellys.mdl
models/tb/tb-maze8/electrical-box.mdl
models/tb/tb-maze8/box1.mdl
models/tb/tb-maze8/oxygen-bottle.mdl
models/tb/tb-maze8/prop_hevmedkit.mdl
models/tb/tb-maze8/prop_hevcharger.mdl
models/tb/tb-maze8/bench1.mdl
models/tb/tb-maze8/rubbish-bins.mdl
models/tb/tb-maze8/wall-aircon-unit.mdl
models/tb/tb-maze8/machinery.mdl
models/tb/tb-maze8/pipe-celing-rusty3.mdl
models/tb/tb-maze8/pipe-celing-rusty1.mdl
models/tb/tb-maze8/industral-pipes4.mdl
models/tb/tb-maze8/industral-pipes5.mdl
models/tb/tb-maze8/equipment_rail2.mdl
models/tb/tb-maze8/old-sackbarrow.mdl
models/tb/tb-maze8/rusty-barrel.mdl
models/tb/tb-maze8/hardhat.mdl
models/tb/tb-maze8/shelves-old1.mdl
models/tb/tb-maze8/radio1-dead.mdl
models/tb/tb-maze8/forklift2.mdl
models/tb/tb-maze8/truck-canvas.mdl
models/tb/tb-maze8/securitykey.mdl
models/tb/tb-maze8/enemy/pit_drone.mdl
models/tb/snipper/p_m40a1.mdl
models/tb/snipper/w_m40a1.mdl
models/tb/snipper/v_m40a1.mdl
models/tb/snipper/w_m40a1clip.mdl
sound/tb/coin.wav
sound/tb/thotei.wav
sound/tb/tb-maze8/ct_fireinhole.wav
sound/tb/tb-maze8/explo_metal01.wav
sound/tb/tb-maze8/towerbell.wav
sound/tb/tb-maze8/erflush.wav
sound/tb/tb-maze8/drips3.wav
sound/tb/tb-maze8/waterdrip.wav
sound/tb/tb-maze8/watergrate.wav
sound/tb/tb-maze8/waterfall.wav