// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/ntc_bk.tga
gfx/env/ntc_dn.tga
gfx/env/ntc_ft.tga
gfx/env/ntc_lf.tga
gfx/env/ntc_rt.tga
gfx/env/ntc_up.tga
models/player/po_bradshaw/po_bradshaw.bmp
models/player/po_bradshaw/po_bradshaw.mdl
models/player/po_damien/po_damien.bmp
models/player/po_damien/po_damien.mdl
models/player/po_finch/po_finch.bmp
models/player/po_finch/po_finch.mdl
models/player/po_fowley/po_fowley.bmp
models/player/po_fowley/po_fowley.mdl
models/player/po_fuller/po_fuller.bmp
models/player/po_fuller/po_fuller.mdl
models/player/po_hamilton/po_hamilton.bmp
models/player/po_hamilton/po_hamilton.mdl
models/player/po_heinbach/po_heinbach.bmp
models/player/po_heinbach/po_heinbach.mdl
models/player/po_legers/po_legers.bmp
models/player/po_legers/po_legers.mdl
models/player/po_leppard/po_leppard.bmp
models/player/po_leppard/po_leppard.mdl
models/player/po_security/po_security.bmp
models/player/po_security/po_security.mdl
models/poke646/items/crossbow_bolt.mdl
models/poke646/misc/checkpoint.mdl
models/poke646/weapons/cmlwbr/p_cmlwbr.mdl
models/poke646/weapons/cmlwbr/v_cmlwbr.mdl
models/poke646/weapons/cmlwbr/w_cmlwbr.mdl
models/vendetta/items/crossbow_bolt.mdl
models/vendetta/items/grenade.mdl
models/vendetta/items/shotgunshell.mdl
models/vendetta/items/w_crossbow_clip.mdl
models/vendetta/items/w_medibox.mdl
models/vendetta/items/w_par21_clip.mdl
models/vendetta/items/w_par21_grenades.mdl
models/vendetta/items/w_par21_grenadest.mdl
models/vendetta/items/w_shotbox.mdl
models/vendetta/items/w_shotboxt.mdl
models/vendetta/misc/crategibs.mdl
models/vendetta/monsters/barney/barney.mdl
models/vendetta/monsters/gman/gman.mdl
models/vendetta/monsters/hgrunt/hgrunt.mdl
models/vendetta/monsters/scientist/scientist.mdl
models/vendetta/props/basketball.mdl
models/vendetta/props/beerbottle.mdl
models/vendetta/props/bench01.mdl
models/vendetta/props/boxes.mdl
models/vendetta/props/can.mdl
models/vendetta/props/canister.mdl
models/vendetta/props/corpse_male1.mdl
models/vendetta/props/corpse_male2.mdl
models/vendetta/props/corpse_male3.mdl
models/vendetta/props/fan.mdl
models/vendetta/props/food_supplies01.mdl
models/vendetta/props/food_supplies02.mdl
models/vendetta/props/foodbags.mdl
models/vendetta/props/fridge_large.mdl
models/vendetta/props/fridge_small.mdl
models/vendetta/props/lada01.mdl
models/vendetta/props/lada02.mdl
models/vendetta/props/mattress.mdl
models/vendetta/props/meat.mdl
models/vendetta/props/piano.mdl
models/vendetta/props/pickup.mdl
models/vendetta/props/radiator.mdl
models/vendetta/props/rubble.mdl
models/vendetta/props/skateboard2.mdl
models/vendetta/props/spade.mdl
models/vendetta/props/tanker.mdl
models/vendetta/props/trash1.mdl
models/vendetta/props/trash2.mdl
models/vendetta/props/trash4.mdl
models/vendetta/props/trashbag.mdl
models/vendetta/props/washbasin.mdl
models/vendetta/props/washing_machine.mdl
models/vendetta/props/watertower.mdl
models/vendetta/weapons/leadpipe/p_leadpipe.mdl
models/vendetta/weapons/leadpipe/v_leadpipe.mdl
models/vendetta/weapons/leadpipe/w_leadpipe.mdl
models/vendetta/weapons/par21/p_par21.mdl
models/vendetta/weapons/par21/v_par21.mdl
models/vendetta/weapons/par21/w_par21.mdl
models/vendetta/weapons/pipebomb/p_pipebomb.mdl
models/vendetta/weapons/pipebomb/p_pipebomb_watch.mdl
models/vendetta/weapons/pipebomb/v_pipebomb.mdl
models/vendetta/weapons/pipebomb/v_pipebomb_watch.mdl
models/vendetta/weapons/pipebomb/w_pipebomb.mdl
models/vendetta/weapons/sawedoff/p_sawedoff.mdl
models/vendetta/weapons/sawedoff/v_sawedoff.mdl
models/vendetta/weapons/sawedoff/w_sawedoff.mdl
sound/poke646/misc/checkpoint_close.wav
sound/poke646/misc/checkpoint_pulse.wav
sound/poke646/misc/checkpoint_survival.wav
sound/poke646/weapons/cmlwbr/cmlwbr_drawback.wav
sound/poke646/weapons/cmlwbr/cmlwbr_fire.wav
sound/poke646/weapons/cmlwbr/cmlwbr_reload.wav
sound/poke646/weapons/cmlwbr/cmlwbr_reload_empty.wav
sound/poke646/weapons/cmlwbr/cmlwbr_zoom.wav
sound/vendetta/ambience/aircon.wav
sound/vendetta/ambience/alien_spawn2.wav
sound/vendetta/ambience/apc.wav
sound/vendetta/ambience/barfan.wav
sound/vendetta/ambience/battle1.wav
sound/vendetta/ambience/battle2.wav
sound/vendetta/ambience/city1.wav
sound/vendetta/ambience/city2.wav
sound/vendetta/ambience/curtain.wav
sound/vendetta/ambience/fire.wav
sound/vendetta/ambience/fire_long.wav
sound/vendetta/ambience/flies.wav
sound/vendetta/ambience/jukebox.wav
sound/vendetta/ambience/lowman.wav
sound/vendetta/ambience/neonlighthum.wav
sound/vendetta/ambience/piano.wav
sound/vendetta/ambience/singledrip.wav
sound/vendetta/ambience/slasher.wav
sound/vendetta/ambience/spawn.wav
sound/vendetta/ambience/truck2.wav
sound/vendetta/ambience/washer.wav
sound/vendetta/buttons/blip1.wav
sound/vendetta/buttons/blip2.wav
sound/vendetta/buttons/button1.wav
sound/vendetta/buttons/button10.wav
sound/vendetta/buttons/button11.wav
sound/vendetta/buttons/button7.wav
sound/vendetta/buttons/button8.wav
sound/vendetta/buttons/spark1.wav
sound/vendetta/buttons/spark2.wav
sound/vendetta/buttons/spark3.wav
sound/vendetta/buttons/spark4.wav
sound/vendetta/buttons/spark5.wav
sound/vendetta/buttons/spark6.wav
sound/vendetta/doors/doormove1.wav
sound/vendetta/hgrunt/freeman!.wav
sound/vendetta/hgrunt/freeman.wav
sound/vendetta/mp3/ntc.mp3
sound/vendetta/plats/freightmove1.wav
sound/vendetta/plats/freightmove2.wav
sound/vendetta/plats/train_brake1.wav
sound/vendetta/plats/train_start1.wav
sound/vendetta/plats/train_use1.wav
sound/vendetta/plats/ttrain1.wav
sound/vendetta/vendetta_materials.txt
sound/vendetta/weapons/leadpipe/leadpipe_breathe.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit1.wav
sound/vendetta/weapons/leadpipe/leadpipe_hit2.wav
sound/vendetta/weapons/leadpipe/leadpipe_miss.wav
sound/vendetta/weapons/par21/par21_fire.wav
sound/vendetta/weapons/par21/par21_gl1.wav
sound/vendetta/weapons/par21/par21_gl2.wav
sound/vendetta/weapons/par21/par21_reload.wav
sound/vendetta/weapons/pipebomb/pipebomb_bounce1.wav
sound/vendetta/weapons/pipebomb/pipebomb_bounce2.wav
sound/vendetta/weapons/pipebomb/pipebomb_bounce3.wav
sound/vendetta/weapons/sawedoff/sawedoff_fire.wav
sound/vendetta/weapons/sawedoff/sawedoff_pump.wav
sound/vendetta/weapons/sawedoff/sawedoff_reload1.wav
sound/vendetta/weapons/sawedoff/sawedoff_reload2.wav
sound/weapons/dryfire.wav
sprites/poke646/cmlwbr.spr
sprites/poke646/po_ammo.spr
sprites/poke646/po_crosshairs.spr
sprites/poke646/weapon_cmlwbr.txt
sprites/vendetta/drips.spr
sprites/vendetta/fire.spr
sprites/vendetta/glow_lantern.spr
sprites/vendetta/leadpipe.spr
sprites/vendetta/levelchange.spr
sprites/vendetta/moths.spr
sprites/vendetta/par21.spr
sprites/vendetta/pv_ammo.spr
sprites/vendetta/pv_crosshairs.spr
sprites/vendetta/sawedoff.spr
sprites/vendetta/weapon_leadpipe.txt
sprites/vendetta/weapon_par21.txt
sprites/vendetta/weapon_sawedoff.txt
vendetta.wad
