// resgen\maps\shl10.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (47):
decals.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
liquids.wad
models/bm_leg.mdl
models/bm_sack.mdl
models/bm_shell.mdl
models/bullsquid.mdl
models/concretegibs.mdl
models/construction.mdl
models/glassgibs.mdl
shl.wad
sound/Ambience/alien_builder.wav
sound/Ambience/alien_chatter.wav
sound/ambience/distantmortar3.wav
sound/ambience/dronemachine2.wav
sound/ambience/flameburst1.wav
sound/ambience/labdrone1.wav
sound/ambience/labdrone2.wav
sound/Ambience/rocketrumble1.wav
sound/ambience/siren.wav
sound/ambience/warn1.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/lightswitch2.wav
sound/debris/beamstart5.wav
sound/debris/beamstart8.wav
sound/debris/glass2.wav
sound/debris/metal6.wav
sound/gonarch/gon_alert1.wav
sound/gonarch/gon_die1.wav
sound/hgrunt/fire!.wav
sound/shl/code.wav
sound/shl/ufo.wav
sound/shl/ufo_bgm.wav
sound/weapons/explode3.wav
sprites/eexplo.spr
sprites/fexplo1.spr
sprites/laserbeam.spr
sprites/nhth1.spr
sprites/xflare2.spr
xeno.wad
sound/shl/hevsci/run1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/m41a_single.wav
sound/shl/spf_reload1.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/dbarrel1.wav
sound/shl/hevbarney/scock1.wav
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav