// shl15.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (48):
decals.wad
gfx/env/alien3bk.tga
gfx/env/alien3dn.tga
gfx/env/alien3ft.tga
gfx/env/alien3lf.tga
gfx/env/alien3rt.tga
gfx/env/alien3up.tga
halflife.wad
liquids.wad
models/big_rock.mdl
models/islave.mdl
models/office_gibs.mdl
models/player.mdl
models/rockgibs.mdl
models/shl/w_xenmedkit.mdl
models/shl/w_xenmedkitt.mdl
shl.wad
sound/agrunt/ag_alert5.wav
sound/ambience/alien_builder.wav
sound/ambience/alien_humongo.wav
sound/ambience/drips.wav
sound/ambience/port_suckin1.wav
sound/ambience/the_horror4.wav
sound/aslave/slv_alert1.wav
sound/debris/beamstart1.wav
sound/debris/beamstart2.wav
sound/debris/beamstart8.wav
sound/debris/bustmetal1.wav
sound/debris/concrete1.wav
sound/debris/zap2.wav
sound/debris/zap7.wav
sound/shl/nuke_explode.wav
sound/shl/pico.wav
sound/shl/radio.wav
sound/shl/ship1.wav
sound/shl/ufo_on.wav
sound/shl/vivaldi1.wav
sound/weapons/mortarhit.wav
sound/x/nih_die2.wav
sprites/fexplo.spr
sprites/fire.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/muz1.spr
sprites/nhth1.spr
sprites/xffloor.spr
sprites/xflare1.spr
sprites/xspark3.spr
xeno.wad
models/shl/hev_sci.mdl
models/shl/hev_sci01.mdl
models/shl/hev_sci02.mdl
models/shl/hev_sci03.mdl
models/shl/hev_sciT.mdl
sound/shl/hevsci_monster.txt
sound/shl/hevsci/run1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/m41a_single.wav
sound/shl/spf_reload1.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/hevbarney/dbarrel1.wav
sound/shl/hevbarney/scock1.wav
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav