// shl13.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (42):
decals.wad
gfx/env/neb7bk.tga
gfx/env/neb7dn.tga
gfx/env/neb7ft.tga
gfx/env/neb7lf.tga
gfx/env/neb7rt.tga
gfx/env/neb7up.tga
halflife.wad
liquids.wad
shl.wad
sound/ambience/alien_beacon.wav
sound/ambience/alien_builder.wav
sound/ambience/alien_hollow.wav
sound/ambience/alien_squit.wav
sound/ambience/alienwind2.wav
sound/ambience/flameburst1.wav
sound/ambience/labmoan.wav
sound/ambience/particle_suck2.wav
sound/ambience/zapmachine.wav
sound/debris/beamstart10.wav
sound/debris/beamstart5.wav
sound/shl/electrical_hum1.wav
sound/nihilanth/nil_thieves.wav
sound/shl/bom.wav
sound/shl/nuke_explode.wav
sound/shl/pkup.wav
sound/shl/shock_discharge.wav
sound/shl/ufo_bgm.wav
sound/shl/xensound0.wav
sprites/c-tele1.spr
sprites/cnt1.spr
sprites/enter1.spr
sprites/fexplo1.spr
sprites/gwave1.spr
sprites/hexplo.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/tele1.spr
sprites/xfireball3.spr
sprites/xflare1.spr
sprites/xspark2.spr
xeno.wad
models/shl/w_xenmedkit.mdl
models/shl/w_xenmedkitt.mdl
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav