// shl11.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (44):
decals.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
liquids.wad
models/concrete_gibs.mdl
models/scigun.mdl
shl.wad
sound/ambience/biggun2.wav
sound/ambience/biggun3.wav
sound/ambience/computalk2.wav
sound/ambience/des_wind1.wav
sound/ambience/jetflyby1.wav
sound/ambience/labmoan.wav
sound/ambience/mechwhine.wav
sound/ambience/mgun_burst1.wav
sound/ambience/mgun_burst4.wav
sound/ambience/port_suckin1.wav
sound/ambience/port_suckout1.wav
sound/ambience/quail1.wav
sound/ambience/signalgear1.wav
sound/ambience/signalgear2.wav
sound/ambience/wren1.wav
sound/debris/beamstart2.wav
sound/debris/concrete3.wav
sound/fvox/bell.wav
sound/fvox/hev_logon.wav
sound/garg/gar_pain2.wav
sound/shl/clasic_1.wav
sound/shl/on.wav
sound/shl/ufo.wav
sound/weapons/egon_windup2.wav
sound/weapons/mortar.wav
sprites/fexplo1.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/muzzleflash2.spr
sprites/xfireball3.spr
sprites/xflare1.spr
xeno.wad
sound/shl/hevsci/run1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/m41a_single.wav
sound/shl/spf_reload1.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/dbarrel1.wav
sound/shl/hevbarney/scock1.wav
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav