// shl12.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (42):
decals.wad
gfx/env/neb7bk.tga
gfx/env/neb7dn.tga
gfx/env/neb7ft.tga
gfx/env/neb7lf.tga
gfx/env/neb7rt.tga
gfx/env/neb7up.tga
halflife.wad
liquids.wad
shl.wad
sound/ambience/alien_cycletone.wav
sound/ambience/alien_frantic.wav
sound/ambience/alien_minddrill.wav
sound/ambience/alien_powernode.wav
sound/ambience/alien_twow.wav
sound/ambience/aliencave1.wav
sound/ambience/alienvoices1.wav
sound/ambience/flameburst1.wav
sound/ambience/port_suckout1.wav
sound/debris/beamstart10.wav
sound/debris/beamstart15.wav
sound/debris/beamstart2.wav
sound/debris/beamstart5.wav
sound/debris/beamstart9.wav
sound/debris/zap1.wav
sound/debris/zap8.wav
sound/garg/gar_alert3.wav
sound/nihilanth/nil_alone.wav
sound/player/breathe2.wav
sound/player/heartbeat1.wav
sound/shl/kaos.wav
sound/shl/ufo.wav
sound/shl/xensound0.wav
sound/shl/xensound1.wav
sound/x/x_laugh2.wav
sprites/b-tele1.spr
sprites/enter1.spr
sprites/fexplo1.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/xflare1.spr
xeno.wad
sound/shl/hevsci/run1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/m41a_single.wav
sound/shl/spf_reload1.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/dbarrel1.wav
sound/shl/hevbarney/scock1.wav
models/shl/w_xenmedkit.mdl
models/shl/w_xenmedkitt.mdl
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav