// shl9.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (47):
decals.wad
gfx/env/neb7bk.tga
gfx/env/neb7dn.tga
gfx/env/neb7ft.tga
gfx/env/neb7lf.tga
gfx/env/neb7rt.tga
gfx/env/neb7up.tga
halflife.wad
liquids.wad
models/cactusgibs.mdl
models/can.mdl
models/crystal.mdl
models/hgibs.mdl
models/metalplategibs_dark.mdl
models/office_gibs.mdl
models/player.mdl
shl.wad
sound/ambience/alien_hollow.wav
sound/ambience/computalk2.wav
sound/ambience/deadsignal2.wav
sound/Ambience/dronemachine2.wav
sound/ambience/labdrone2.wav
sound/Ambience/labgear.wav
sound/ambience/particle_suck2.wav
sound/ambience/port_suckin1.wav
sound/ambience/pulsemachine.wav
sound/ambience/the_horror3.wav
sound/debris/beamstart1.wav
sound/doors/doormove5.wav
sound/nihilanth/nil_deceive.wav
sound/shl/mecanical.wav
sound/shl/piano.wav
sound/scientist/c3a2_sci_1surv.wav
sound/shl/set.wav
sound/tentacle/te_death2.wav
sound/weapons/mine_activate.wav
sound/weapons/mortarhit.wav
sprites/e-tele1.spr
sprites/fexplo1.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/laserbeam.spr
sprites/lgtning.spr
sprites/portal1.spr
sprites/xenobeam.spr
sprites/xflare1.spr
xeno.wad
models/shl/hevsci.mdl
models/shl/hev_sci.mdl
models/shl/hev_sci01.mdl
models/shl/hev_sci02.mdl
models/shl/hev_sci03.mdl
models/shl/hev_sciT.mdl
sound/shl/hevsci_monster.txt
sound/shl/hevsci/run1.wav
sound/shl/hevbarney/hks1.wav
sound/shl/hevbarney/hks2.wav
sound/shl/hevbarney/hks3.wav
sound/shl/m41a_3round.wav
sound/shl/m41aglauncher.wav
sound/shl/m41aglauncher2.wav
sound/shl/m41a_single.wav
sound/shl/spf_reload1.wav
sound/shl/hevbarney/sbarrel1.wav
sound/shl/dbarrel1.wav
sound/shl/hevbarney/scock1.wav
models/shl/race.mdl
models/shl/racet.mdl
sound/shl/ufo_monster.txt
sound/shl/race/alert1.wav
sound/shl/race/alert2.wav
sound/shl/race/die1.wav
sound/shl/race/die2.wav
sound/shl/race/idle1.wav
sound/shl/race/idle2.wav
sound/shl/race/idle3.wav
sound/shl/race/idle4.wav
sound/shl/race/idle5.wav
sound/shl/race/pain1.wav
sound/shl/race/pain2.wav
sound/shl/race/pain3.wav
sound/shl/race/pain4.wav
sound/shl/race/pain5.wav
sound/shl/weapons/plasma1.wav
sound/shl/weapons/plasma2.wav