events/muzzle_bowcasterblaster.txt
events/muzzle_dl44blaster.txt
events/muzzle_vulcan.txt
events/muzzle_rifleblaster.txt
events/muzzle_rifleblasternpc.txt
events/muzzle_t21blaster.txt
//
models/portalhouse/BlasterShootRed.mdl
models/portalhouse/FlechetteShoot.mdl
models/portalhouse/HighPowerBlasterShootRed.mdl
models/portalhouse/p_bowcaster.mdl
models/portalhouse/p_dl44.mdl
models/portalhouse/p_dl44Null.mdl
models/portalhouse/p_plasmagun.mdl
models/portalhouse/p_rifleBlaster.mdl
models/portalhouse/p_t21.mdl
models/portalhouse/race.mdl
models/portalhouse/v_bowcaster.mdl
models/portalhouse/v_dl44.mdl
models/portalhouse/v_plasmagun.mdl
models/portalhouse/v_rifleBlaster.mdl
models/portalhouse/v_t21.mdl
models/portalhouse/w_bowcaster.mdl
models/portalhouse/w_dl44.mdl
models/portalhouse/w_plasmagun.mdl
models/portalhouse/w_rifleBlaster.mdl
models/portalhouse/w_t21.mdl
//
sound/portalhouse/alt_explodeHeavyRepeater.wav
sound/portalhouse/alt_fireBowcaster.wav
sound/portalhouse/alt_fireHeavyRepeater.wav
sound/portalhouse/dryfire.wav
sound/portalhouse/fireBowcaster.wav
sound/portalhouse/fireHeavyRepeater.wav
sound/portalhouse/fireT21.wav
sound/portalhouse/hit_wallBowcaster.wav
sound/portalhouse/hit_wallHeavyRepeater.wav
sound/portalhouse/hit_wallRifleBlaster.wav
sound/portalhouse/hks1.wav
sound/portalhouse/selectBowcaster.wav
sound/portalhouse/selectRifleBlaster.wav
sound/portalhouse/shootRifleBlaster.wav
//
sound/portalhouse/monsters/anger2.wav
sound/portalhouse/monsters/chase2.wav
sound/portalhouse/monsters/chase3.wav
sound/portalhouse/monsters/death1.wav
sound/portalhouse/monsters/death2.wav
sound/portalhouse/monsters/death3.wav
sound/portalhouse/monsters/detected5.wav
sound/portalhouse/monsters/follow.wav
sound/portalhouse/monsters/pain25.wav
sound/portalhouse/monsters/pain50.wav
sound/portalhouse/monsters/pain75.wav
sound/portalhouse/monsters/pain100.wav
sound/portalhouse/monsters/stopfollow.wav
sound/portalhouse/monsters/victory1.wav
sound/portalhouse/monsters/victory3.wav
//
sprites/portalhouse/640hud1.spr
sprites/portalhouse/640hud4.spr
sprites/portalhouse/640hudas1.spr
sprites/portalhouse/640hudas4.spr
sprites/portalhouse/ammo.spr
sprites/portalhouse/blasterboltred.spr
sprites/portalhouse/blasterimpact.spr
sprites/portalhouse/crosshairs.spr
sprites/portalhouse/crosshairsas.spr
sprites/portalhouse/cshoot.spr
sprites/portalhouse/expB1.spr
sprites/portalhouse/weapon_BowcasterBlaster.txt
sprites/portalhouse/weapon_DL44Blaster.txt
sprites/portalhouse/weapon_plasmagun.txt
sprites/portalhouse/weapon_t12blaster.txt
sprites/portalhouse/weapon_9mmm41a.txt
sprites/portalhouse/weapon_ofshockrifle.txt
